[build-system]
requires = ["Sphinx", "build", "doit", "flake8", "pydocstyle", "setuptools", "babel", "os", "sys", "itertools", "abc", "unittest", "tkinter", "gettext", "collections"]
build-backend = "setuptools.build_meta"